(()=>{
const AXES=[['insult','侮辱'],['threat','脅迫'],['identity_attack','属性攻撃'],['indirect_hostility','間接敵意'],['obscene','卑俗'],['sexual_explicit','性的']];
let enabled=true;chrome.storage.local.get({hoverEnabled:true},x=>enabled=x.hoverEnabled);chrome.storage.onChanged.addListener(c=>{if(c.hoverEnabled)enabled=c.hoverEnabled.newValue});
const cache=new Map();let tooltip=null,hoverTimer=null,current=null,compose=null;
const cls=c=>c==='毒チワワ'?'poison':c==='エロチワワ'?'ero':c==='毒エロチワワ'?'both':'plain';
const pct=v=>`${(100*Number(v||0)).toFixed(0)}%`;
function html(r){return `<div class="jp-off-head"><img src="${chrome.runtime.getURL('icons/icon48.png')}" alt=""><span class="jp-off-class ${cls(r.classification)}">${r.classification}</span><span style="margin-left:auto;opacity:.72;font-size:10px">毒${pct(r.toxic_score)} / エロ${pct(r.erotic_score)}</span></div><div class="jp-off-mini">${AXES.map(([k,l])=>`<div class="jp-off-mini-row"><span>${l}</span><div class="jp-off-mini-track"><i style="width:${Math.min(100,Math.max(0,(r.scores[k]||0)*100))}%"></i></div><b>${pct(r.scores[k])}</b></div>`).join('')}</div>`}
function position(el,rect,w=270){const left=Math.max(8,Math.min(innerWidth-w-8,rect.left));const top=rect.top>150?rect.top-142:rect.bottom+8;el.style.left=`${scrollX+left}px`;el.style.top=`${scrollY+Math.max(8,top)}px`}
function removeTip(){tooltip?.remove();tooltip=null}
function tweetText(article){for(const el of article.querySelectorAll('[data-testid="tweetText"]')){const t=el.innerText?.trim();if(t)return t}return ''}
async function infer(text){if(cache.has(text))return cache.get(text);const x=await chrome.runtime.sendMessage({type:'INFER',text});if(!x?.ok)throw Error(x?.error||'推論失敗');cache.set(text,x.result);return x.result}
async function showFor(article){const text=tweetText(article);if(!text)return;removeTip();const rect=article.getBoundingClientRect();const el=document.createElement('div');el.className='jp-off-tooltip';el.innerHTML='<div class="jp-off-loading">チワワ判定中…</div>';document.documentElement.appendChild(el);position(el,rect);tooltip=el;try{const r=await infer(text);if(tooltip===el)el.innerHTML=html(r)}catch(e){el.remove();if(tooltip===el)tooltip=null}}
document.addEventListener('mouseover',e=>{if(!enabled||!/^https?:\/\/(www\.)?(x\.com|twitter\.com)\//.test(location.href))return;const a=e.target.closest?.('article[data-testid="tweet"]');if(!a||a===current)return;clearTimeout(hoverTimer);current=a;hoverTimer=setTimeout(()=>showFor(a),350)},true);
document.addEventListener('mouseout',e=>{const a=e.target.closest?.('article[data-testid="tweet"]');if(!a||a!==current||a.contains(e.relatedTarget))return;clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>{removeTip();current=null},200)},true);
function ensureCompose(){if(compose?.isConnected)return compose;compose=document.createElement('section');compose.className='jp-off-compose';compose.innerHTML=`<div class="jp-off-compose-head"><strong class="jp-off-compose-title"><img src="${chrome.runtime.getURL('icons/icon48.png')}" alt="">投稿前チワワチェック</strong><button class="jp-off-close">×</button></div><textarea maxlength="5000" placeholder="チェックする文章を入力"></textarea><div class="jp-off-compose-actions"><span class="jp-off-compose-status">入力中に自動評価</span><button class="jp-off-copy">コピーする</button></div><div class="jp-off-compose-result" hidden></div>`;document.documentElement.appendChild(compose);const ta=compose.querySelector('textarea'),res=compose.querySelector('.jp-off-compose-result'),st=compose.querySelector('.jp-off-compose-status');compose.querySelector('.jp-off-close').onclick=()=>compose.remove();let timer;async function run(){const t=ta.value.trim();if(!t){res.hidden=true;st.textContent='入力中に自動評価';return}st.textContent='チワワ判定中…';try{const r=await infer(t);res.hidden=false;res.innerHTML=`<div class="jp-off-tooltip">${html(r)}</div>`;st.textContent='自動評価済み'}catch(e){st.textContent=`エラー: ${e.message}`}}ta.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(run,350)});compose.querySelector('.jp-off-copy').onclick=async()=>{if(ta.value.trim())try{await navigator.clipboard.writeText(ta.value.trim());st.textContent='コピー済み'}catch{st.textContent='コピーできませんでした'}};const head=compose.querySelector('.jp-off-compose-head');let drag=false,dx=0,dy=0;head.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=compose.getBoundingClientRect();drag=true;dx=e.clientX-r.left;dy=e.clientY-r.top;head.setPointerCapture(e.pointerId)});head.addEventListener('pointermove',e=>{if(!drag)return;compose.style.left=`${Math.max(0,Math.min(innerWidth-compose.offsetWidth,e.clientX-dx))}px`;compose.style.top=`${Math.max(0,Math.min(innerHeight-compose.offsetHeight,e.clientY-dy))}px`;compose.style.right='auto';compose.style.bottom='auto'});head.addEventListener('pointerup',()=>drag=false);return compose}
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='OPEN_COMPOSE'){const c=ensureCompose(),ta=c.querySelector('textarea');ta.value=m.text||'';ta.focus();ta.dispatchEvent(new Event('input'))}});
})();
