import { AutoTokenizer, env } from "@huggingface/transformers";
import * as ort from "onnxruntime-web/wasm";
import { MODEL_ID, TOKENIZER_ID, MODEL_URL, MODEL_META_URL, MODEL_CACHE, MAX_LENGTH, AXES } from "./constants.js";
env.allowRemoteModels=true; env.allowLocalModels=true; env.useBrowserCache=true;
ort.env.wasm.numThreads=1; ort.env.wasm.wasmPaths=chrome.runtime.getURL("vendor/");
let tokenizer=null,session=null,metrics=null; let state={phase:"idle",detail:"未初期化",progress:null,error:null};
const set=(p)=>Object.assign(state,p); const to64=(d)=>{const x=new BigInt64Array(d.length);for(let i=0;i<d.length;i++){const id=Number(d[i]);x[i]=BigInt(Number.isFinite(id)&&id>=0&&id<32000?id:1);}return x;};
async function get(url,label){const c=await caches.open(MODEL_CACHE),q=new Request(url,{mode:"cors",credentials:"omit"});let r=await c.match(q);if(r)return r;const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),60000);try{r=await fetch(q,{signal:ctl.signal});}catch(e){throw Error(`${label} download failed: ${e.name==="AbortError"?"タイムアウト（60秒）":e.message}`);}finally{clearTimeout(timer);}if(!r.ok)throw Error(`${label} download failed: HTTP ${r.status}`);await c.put(q,r.clone());return r;}
async function ensure(){if(tokenizer&&session&&metrics)return;set({phase:"loading",detail:"モデル情報を取得中",error:null});metrics=await(await get(MODEL_META_URL,"model_meta.json")).json();set({phase:"loading",detail:"Tokenizerを準備中",error:null});tokenizer=await AutoTokenizer.from_pretrained(chrome.runtime.getURL("tokenizer"));set({phase:"loading",detail:"推論モデルを準備中",error:null});const b=await(await get(MODEL_URL,"model")).arrayBuffer();session=await ort.InferenceSession.create(b,{executionProviders:["wasm"],graphOptimizationLevel:"all"});set({phase:"ready",detail:"モデル準備完了",progress:1});}
async function infer(text){await ensure();const e=await tokenizer(String(text).trim(),{truncation:true,max_length:MAX_LENGTH,padding:"max_length"}),f={};for(const n of ["input_ids","attention_mask"]){const t=e[n];if(!t)throw Error(`Tokenizer出力に${n}がありません`);const ids=Array.from(t.data).slice(0,MAX_LENGTH);f[n]=new ort.Tensor("int64",to64(ids),[1,ids.length]);}const o=await session.run(f),raw=Array.from((o.scores||o[session.outputNames[0]]).data),scores={};AXES.forEach((axis,i)=>scores[axis]=Math.max(0,Math.min(1,Number(raw[i]))));const hostile=Math.max(scores.insult,scores.threat,scores.identity_attack,scores.indirect_hostility),content=Math.max(scores.obscene,scores.sexual_explicit),toxic=hostile>=.5,erotic=content>=.5;return{text:String(text).trim(),scores,toxicity_score:hostile,content_risk_score:content,toxic,erotic,decision:toxic&&erotic?"毒エロチワワ":toxic?"毒チワワ":erotic?"エロチワワ":"ただのチワワ",model_id:MODEL_ID};}
chrome.runtime.onMessage.addListener((m,s,send)=>{if(!m?.__fromServiceWorker)return false;(async()=>{if(m.type==="GET_STATUS")return{ok:true,state:{...state}};if(m.type==="PREPARE_MODEL"){await ensure();return{ok:true,state:{...state}};}if(m.type==="INFER")return{ok:true,result:await infer(m.text)};if(m.type==="CLEAR_MODEL_CACHE"){await caches.delete(MODEL_CACHE);tokenizer=session=metrics=null;set({phase:"idle",detail:"キャッシュ削除済み",error:null});return{ok:true};}})().then(send).catch(e=>send({ok:false,error:String(e?.message||e),state:{...state}}));return true;});
